import React from "react";
import {Link} from 'react-router-dom';
import styled from 'styled-components';
import logo from '../../assets/img/CCDC_Logo.svg';

const LogoBanner = styled.div`
  width: 100%;
`;

const LogoContainer = styled.div`
  width: 1200px;
  margin: 0 auto;
`;

const Logo = styled.img`
  height: 100px;
`;

const SearchArea = styled.div`
  float: right;
  display: flex;
  border: 2px solid #29c89a;
  border-radius: 18px;
  padding: 5px 10px 5px 15px;
  color: #29c89a;
  font-size: 1rem;
  font-weight: 400;
  margin-top: 30px;
`;

const SearchIcon = styled.div`
  color: #29c89a;
  font-size: 1.1rem;
  font-weight: 600;
`;

const SearchInput = styled.input`
  border: none;
  color: #29c89a;
  font-size: 1rem;
  font-weight: 600;
  width: 150px;
  margin-left: 5px;

  ::placeholder {
    color: #29c89a;
    font-size: 1rem;
    font-weight: 600;
  }

  :focus {
    outline: none;
  }
`;

const SearchRadio = styled.input`
  color: #29c89a;
  -webkit-appearance: none;
  appearance: none;
  margin: 4px 5px 0 5px;
  color: #29c89a;
  width: 1.15em;
  height: 1.15em;
  border: 0.15em solid #29c89a;
  border-radius: 50%;
  transform: translateY(-0.075em);
  display: grid;
  place-content: center;
  
  ::before {
    content: "";
    width: 0.65em;
    height: 0.65em;
    border-radius: 50%;
    transform: scale(0);
    transition: 120ms transform ease-in-out;
    box-shadow: inset 1em 1em var(--form-control-color);
    background-color: #29c89a;
  }
  
  :checked::before {
    transform: scale(1);
  }
`;

const HeaderBar = styled.div`
  width: 100%;
  background-color: #e3e3e3;
`;

const HeaderContainer = styled.div`
  width: 1200px;
  margin: 0 auto;
  padding: 10px 0 10px 25px;
  color: #606061;
  font-size: 1rem;
  font-weight: 600;

`;

const Header = () => {
    return (
      <>
      <LogoBanner role="banner">
        <LogoContainer>
          <Link to="/"><Logo src={logo} alt="logo" /></Link>
          <SearchArea>
            <SearchIcon>
              <i className="fas fa-search" />
            </SearchIcon>
            <SearchInput type="text" placeholder="Search CCDC" />
            <SearchRadio type="radio" name="search_type" checked="true" />
            Dataset
            <SearchRadio type="radio" name="search_type" />
            Document
          </SearchArea>
        </LogoContainer>
      </LogoBanner>
      <HeaderBar>
        <HeaderContainer>
          Sharing clinical care and research data generated by the pediatric cancer research community
        </HeaderContainer>
      </HeaderBar>
      </>
  );
};

export default Header;